const DEFAULT={schemaVersion:3,initial:4600,cideMonthly:900,rebecaMonthly:0,months:33,reserveFloor:10000,cideShare:80,schedule:{dating:'2027-01',contributions:'2027-01',engagement:'2028-01',wedding:'2029-09'},milestones:[{id:'dating',kind:'dating',date:'2027-01',title:'Início do namoro',description:'Alinhar valores, rotina e propósito.',status:'Em andamento',locked:true},{id:'engagement',kind:'engagement',date:'2028-01',title:'Noivado',description:'Teto de R$ 2.000; pagar à vista.',status:'Marco',locked:true},{id:'quotes',date:'2028-03',offsetMonths:-18,title:'Primeiras cotações',description:'Civil, alimentação, espaço, fotografia e trajes.',status:'Decisão conjunta'},{id:'gate',date:'2029-01',offsetMonths:-8,title:'Portão de viabilidade',description:'Confirmar renda, aluguel real em Manaus e orçamento final.',status:'Obrigatório'},{id:'contracts',date:'2029-06',offsetMonths:-3,title:'Contratos essenciais',description:'Contratar apenas o que estiver coberto.',status:'Sem dívida'},{id:'wedding',kind:'wedding',date:'2029-09',title:'Casamento e início do aluguel',description:'Preservar reserva mínima e medir o custo real.',status:'Meta',locked:true}],goals:{engagement:2000,wedding:12000,honeymoon:5000,home:4000,reserve:36000},budget:[['Civil e documentos',800],['Espaço e alimentação',5200],['Decoração',1600],['Fotografia',1800],['Trajes e beleza',1300],['Convites e lembranças',700],['Imprevistos',600]],home:[['Aluguel',1100],['Alimentação',850],['Energia, água e gás',300],['Internet e celulares',200],['Transporte',300],['Saúde e higiene',150],['Outros essenciais',100]],contributions:[],reviews:[false,false,false,false,false,false,false,false,false,false,false]};
let state=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const sum=a=>a.reduce((t,v)=>t+Number(v||0),0); const totalGoal=()=>sum(Object.values(state.goals)); const projected=()=>state.initial+state.months*(state.cideMonthly+state.rebecaMonthly)+sum(state.contributions.map(x=>x.amount));
const monthDate=value=>{const [year,month]=value.split('-').map(Number);return new Date(year,month-1,1)};
const monthCount=(start,end)=>{const a=monthDate(start),b=monthDate(end);return Math.max(1,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()+1)};
const monthLabel=(value,short=false)=>monthDate(value).toLocaleDateString('pt-BR',{month:short?'short':'long',year:'numeric'}).replace('.','');
const monthOnly=value=>monthDate(value).toLocaleDateString('pt-BR',{month:'short'}).replace('.','').toUpperCase();
const shiftMonth=(value,offset)=>{const date=monthDate(value);date.setMonth(date.getMonth()+offset);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`};
const safe=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const welcome=$('#welcome'),enterPlan=$('#enter-plan');
enterPlan?.addEventListener('click',()=>{
  welcome.classList.add('leaving');
  document.body.classList.remove('welcome-active');
  setTimeout(()=>{welcome.hidden=true;$('#conteudo').focus({preventScroll:true})},720);
});
function load(){try{const saved=JSON.parse(localStorage.getItem('alianca-financeira')||'{}');if(!saved.schemaVersion){saved.initial=4600;saved.schemaVersion=2}return merge(DEFAULT,saved)}catch{return structuredClone(DEFAULT)}}
function merge(base,extra){const out={...structuredClone(base),...extra};out.goals={...base.goals,...(extra.goals||{})};out.schedule={...base.schedule,...(extra.schedule||{})};out.milestones=Array.isArray(extra.milestones)?extra.milestones:structuredClone(base.milestones);const [sy,sm]=out.schedule.contributions.split('-').map(Number),[ey,em]=out.schedule.wedding.split('-').map(Number);out.months=Math.max(1,(ey-sy)*12+em-sm+1);out.schemaVersion=3;return out}
function save(){localStorage.setItem('alianca-financeira',JSON.stringify(state));renderAll()}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id&&b.classList.contains('nav-item')));$('#page-title').textContent=$('#'+id)?.dataset.title||'Aliança Financeira';location.hash=id;$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');if(id==='dashboard')requestAnimationFrame(drawChart);scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#menu').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open)};
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('alianca-theme',document.body.classList.contains('dark')?'dark':'light');drawChart()};if(localStorage.getItem('alianca-theme')==='dark')document.body.classList.add('dark');
function renderDashboard(){const target=totalGoal(),proj=projected(),gap=Math.max(0,target-proj),extra=gap/state.months,wedding=monthLabel(state.schedule.wedding),engagement=monthLabel(state.schedule.engagement);$('#m-initial').textContent=money(state.initial);$('#m-projected').textContent=money(proj);$('#m-contrib').textContent=`${money(state.cideMonthly+state.rebecaMonthly)}/mês + registros`;$('#m-target').textContent=money(target);$('#m-gap').textContent=gap?money(gap):'Meta alcançada';$('#m-extra').textContent=gap?`Faltam ${money(extra)}/mês`:'Existe margem de segurança';$('#months-pill').textContent=`${state.months} meses`;$('#welcome-wedding-date').textContent=wedding;$('#hero-wedding-title').textContent=`Casamento em ${wedding}`;$('#hero-wedding-month').textContent=monthOnly(state.schedule.wedding);$('#hero-wedding-year').textContent=state.schedule.wedding.slice(0,4);$('#engagement-date').textContent=engagement;$('#guide-total').textContent=money(target);const gate=$('.gate');gate.classList.toggle('good',gap===0);$('#gate-title').textContent=gap?'Plano exige ajuste':'Plano financeiramente viável';$('#gate-copy').textContent=gap?`É preciso adicionar ${money(extra)} por mês, reduzir metas ou aumentar a renda.`:`A projeção cobre as metas e preserva a reserva planejada.`;const items=[['Noivado',state.goals.engagement,monthLabel(state.schedule.engagement,true),'gold'],['Celebração',state.goals.wedding,monthLabel(state.schedule.wedding,true),'teal'],['Lua de mel',state.goals.honeymoon,monthLabel(state.schedule.wedding,true),'rose'],['Casa inicial',state.goals.home,monthLabel(state.schedule.wedding,true),'navy'],['Reserva de 12 meses',state.goals.reserve,'Proteção','green']];$('#goal-list').innerHTML=items.map(x=>`<div class="goal-item ${x[3]}"><span>${x[0]}</span><strong>${money(x[1])}</strong><small>${x[2]}</small></div>`).join('');drawChart()}
function drawChart(){const c=$('#chart');if(!c)return;const w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;const dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);const pad={l:45,r:16,t:18,b:30},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,target=totalGoal(),max=Math.max(target,projected())*1.08;x.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');x.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');x.font='12px Manrope';for(let i=0;i<5;i++){const y=pad.t+ch*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText(money(max*(1-i/4)).replace(',00',''),0,y+4)}const line=(color,fn,dash=[])=>{x.strokeStyle=color;x.lineWidth=3;x.setLineDash(dash);x.beginPath();for(let m=0;m<=state.months;m++){const xx=pad.l+cw*m/state.months,yy=pad.t+ch*(1-fn(m)/max);m?x.lineTo(xx,yy):x.moveTo(xx,yy)}x.stroke();x.setLineDash([])};line(getComputedStyle(document.body).getPropertyValue('--gold'),m=>target*m/state.months,[7,6]);line(getComputedStyle(document.body).getPropertyValue('--teal'),m=>state.initial+m*(state.cideMonthly+state.rebecaMonthly));x.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');const labels=[[monthLabel(state.schedule.contributions,true),0],[monthLabel(state.schedule.engagement,true),Math.min(state.months-1,Math.max(0,monthCount(state.schedule.contributions,state.schedule.engagement)-1))],[monthLabel(state.schedule.wedding,true),state.months-1]];labels.forEach(([t,m])=>x.fillText(t,pad.l+(cw-45)*(m/Math.max(1,state.months-1)),h-7))}
function renderGoals(){const defs=[['engagement','Noivado','Teto provisório para alianças, pedido e uma celebração simples'],['wedding','Casamento civil e celebração','Até 30 pessoas; cerimônia ainda será decidida'],['honeymoon','Lua de mel','Meta separada para transporte, hospedagem, alimentação e margem de segurança'],['home','Casa inicial','Mudança, itens básicos e instalação'],['reserve','Reserva de 12 meses','Complemento temporário de renda após o casamento']];$('#goal-inputs').innerHTML=defs.map(([k,t,d])=>`<div class="field-card"><label>${t}<input data-goal="${k}" type="number" min="0" step="100" value="${state.goals[k]}"></label><small>${d}</small></div>`).join('');$$('[data-goal]').forEach(i=>i.onchange=()=>{state.goals[i.dataset.goal]=Number(i.value);save();toast('Meta atualizada')});$('#reserve-floor-label').textContent=money(state.reserveFloor)}
function renderBudget(){const box=$('#budget-table');box.innerHTML=state.budget.map((r,i)=>`<div class="budget-row"><input aria-label="Categoria" data-budget-name="${i}" value="${r[0]}"><input aria-label="Valor da categoria" data-budget-value="${i}" type="number" min="0" value="${r[1]}"><button aria-label="Remover categoria" data-budget-remove="${i}">×</button></div>`).join('')+`<button class="text-btn" id="add-budget">+ Adicionar categoria</button>`;const used=sum(state.budget.map(x=>x[1])),limit=state.goals.wedding;$('#budget-sum').textContent=money(used);$('#budget-status').textContent=used<=limit?`${money(limit-used)} disponíveis`:`${money(used-limit)} acima do teto`;$('#budget-status').style.color=used<=limit?'var(--green)':'var(--red)';$$('[data-budget-name]').forEach(i=>i.onchange=()=>{state.budget[i.dataset.budgetName][0]=i.value;save()});$$('[data-budget-value]').forEach(i=>i.onchange=()=>{state.budget[i.dataset.budgetValue][1]=Number(i.value);save()});$$('[data-budget-remove]').forEach(b=>b.onclick=()=>{state.budget.splice(b.dataset.budgetRemove,1);save()});$('#add-budget').onclick=()=>{state.budget.push(['Nova categoria',0]);save()}}
function renderContributions(){const total=sum(state.contributions.map(x=>x.amount));$('#contribution-total').textContent=money(total);$('#contribution-list').innerHTML=state.contributions.length?state.contributions.slice().reverse().map((r,j)=>{const i=state.contributions.length-1-j;return `<div class="record"><div><strong>${r.person}</strong><small>${new Date(r.date+'T12:00:00').toLocaleDateString('pt-BR')} · ${r.note||'Sem observação'}</small></div><strong>${money(r.amount)}</strong><button aria-label="Excluir aporte" data-contribution-remove="${i}">×</button></div>`}).join(''):'<p class="empty">Nenhum aporte registrado ainda.</p>';$$('[data-contribution-remove]').forEach(b=>b.onclick=()=>{state.contributions.splice(b.dataset.contributionRemove,1);save();toast('Aporte removido')})}
$('#contribution-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.contributions.push({date:f.get('date'),person:f.get('person'),amount:Number(f.get('amount')),note:f.get('note')});e.target.reset();save();toast('Aporte registrado')};
function renderTimeline(){state.milestones.forEach(item=>{if(item.kind&&state.schedule[item.kind])item.date=state.schedule[item.kind]});$('#timeline-period').textContent=`${monthLabel(state.schedule.dating).toUpperCase()} — ${monthLabel(state.schedule.wedding).toUpperCase()}`;$('#schedule-months').textContent=`${state.months} ${state.months===1?'mês':'meses'} de contribuição`;$('#date-dating').value=state.schedule.dating;$('#date-contributions').value=state.schedule.contributions;$('#date-engagement').value=state.schedule.engagement;$('#date-wedding').value=state.schedule.wedding;$('#timeline').innerHTML=state.milestones.map((item,i)=>`<article class="timeline-item editable-milestone"><i class="timeline-dot"></i><div class="milestone-fields"><label>Mês<input data-milestone-date="${i}" type="month" value="${safe(item.date)}" ${item.locked?'disabled':''}></label><label>Título<input data-milestone-title="${i}" maxlength="55" value="${safe(item.title)}"></label><label class="wide">Descrição<input data-milestone-description="${i}" maxlength="120" value="${safe(item.description)}"></label><label>Status<input data-milestone-status="${i}" maxlength="30" value="${safe(item.status)}"></label></div><div class="milestone-actions"><span class="pill">${safe(monthLabel(item.date))}</span><button class="mini-action" data-move-up="${i}" aria-label="Mover ${safe(item.title)} para cima" ${i===0?'disabled':''}>↑</button><button class="mini-action" data-move-down="${i}" aria-label="Mover ${safe(item.title)} para baixo" ${i===state.milestones.length-1?'disabled':''}>↓</button>${item.locked?'<span class="core-label">Etapa principal</span>':`<button class="mini-action remove" data-remove-milestone="${i}">Excluir</button>`}</div></article>`).join('');const update=(selector,key)=>$$(selector).forEach(input=>input.onchange=()=>{const item=state.milestones[Number(input.dataset[Object.keys(input.dataset)[0]])];item[key]=input.value.trim();if(key==='date')delete item.offsetMonths;save();toast('Etapa atualizada')});update('[data-milestone-date]','date');update('[data-milestone-title]','title');update('[data-milestone-description]','description');update('[data-milestone-status]','status');$$('[data-move-up]').forEach(button=>button.onclick=()=>moveMilestone(Number(button.dataset.moveUp),-1));$$('[data-move-down]').forEach(button=>button.onclick=()=>moveMilestone(Number(button.dataset.moveDown),1));$$('[data-remove-milestone]').forEach(button=>button.onclick=()=>{state.milestones.splice(Number(button.dataset.removeMilestone),1);save();toast('Etapa excluída')})}
function moveMilestone(index,direction){const target=index+direction;if(target<0||target>=state.milestones.length)return;[state.milestones[index],state.milestones[target]]=[state.milestones[target],state.milestones[index]];save();toast('Cronograma reorganizado')}
function updateSchedule(){const next={dating:$('#date-dating').value,contributions:$('#date-contributions').value,engagement:$('#date-engagement').value,wedding:$('#date-wedding').value},help=$('#schedule-help');if(Object.values(next).some(value=>!value)){help.textContent='Preencha todas as datas principais.';help.classList.add('error');return}if(next.contributions>next.wedding||next.dating>next.wedding||next.engagement>next.wedding){help.textContent='Namoro, aportes e noivado precisam ocorrer antes do casamento.';help.classList.add('error');return}state.schedule=next;state.months=monthCount(next.contributions,next.wedding);state.milestones.forEach(item=>{if(Number.isInteger(item.offsetMonths))item.date=shiftMonth(next.wedding,item.offsetMonths)});help.classList.remove('error');save();toast('Datas e projeções recalculadas')}
['dating','contributions','engagement','wedding'].forEach(key=>$('#date-'+key).onchange=updateSchedule);
$('#milestone-form').onsubmit=event=>{event.preventDefault();const data=new FormData(event.target);state.milestones.push({id:`custom-${Date.now()}`,date:data.get('date'),title:data.get('title').trim(),description:data.get('description').trim(),status:data.get('status').trim()});event.target.reset();save();toast('Nova etapa adicionada')};
function renderScenario(){const els=['initial','cide','rebeca'];const vals=[state.initial,state.cideMonthly,state.rebecaMonthly];els.forEach((k,i)=>{$('#s-'+k).value=vals[i]});calcScenario()}
function calcScenario(){const initial=Number($('#s-initial').value),cide=Number($('#s-cide').value),rebeca=Number($('#s-rebeca').value),proj=initial+state.months*(cide+rebeca),target=totalGoal(),gap=Math.max(0,target-proj),extra=gap/state.months;$('#scenario-period').textContent=`RESULTADO EM ${monthLabel(state.schedule.wedding).toUpperCase()}`;$('#s-initial-out').textContent=money(initial);$('#s-cide-out').textContent=money(cide)+'/mês';$('#s-rebeca-out').textContent=money(rebeca)+'/mês';$('#s-projected').textContent=money(proj);$('#s-target').textContent=money(target);$('#s-gap').textContent=gap?money(gap):'R$ 0';$('#s-extra').textContent=gap?money(extra)+'/mês':'Nenhum';$('#s-bar').style.width=Math.min(100,proj/target*100)+'%';$('#s-message').textContent=gap?`Neste cenário, a meta ainda não fecha. O casal pode combinar ${money(extra)} a mais por mês ou rever o orçamento.`:`Neste cenário, todas as metas são cobertas até ${monthLabel(state.schedule.wedding)}.`}
['initial','cide','rebeca'].forEach(k=>$('#s-'+k).oninput=calcScenario);$('#apply-scenario').onclick=()=>{state.initial=Number($('#s-initial').value);state.cideMonthly=Number($('#s-cide').value);state.rebecaMonthly=Number($('#s-rebeca').value);save();toast('Cenário aplicado ao plano')};
function renderHome(){const box=$('#home-budget');box.innerHTML=state.home.map((r,i)=>`<label class="home-row"><span>${r[0]}</span><input data-home="${i}" type="number" min="0" value="${r[1]}"></label>`).join('');const total=sum(state.home.map(x=>x[1])),cide=total*state.cideShare/100;$('#home-total').textContent=money(total);$('#home-cide').textContent=money(cide);$('#home-rebeca').textContent=money(total-cide);$('#months-covered').textContent=(state.goals.reserve/total).toLocaleString('pt-BR',{maximumFractionDigits:1})+' meses';$('#donut').style.background=`conic-gradient(var(--teal) 0 ${state.cideShare}%,var(--gold) ${state.cideShare}%)`;$('#donut span').innerHTML=`${state.cideShare}%<small>Cide</small>`;$$('[data-home]').forEach(i=>i.onchange=()=>{state.home[i.dataset.home][1]=Number(i.value);save()})}
function renderReviews(){const dates=['Jan 2027','Abr 2027','Jul 2027','Out 2027','Jan 2028','Abr 2028','Jul 2028','Out 2028','Jan 2029','Abr 2029','Jul 2029'];$('#reviews').innerHTML=dates.map((d,i)=>`<article class="review-card ${state.reviews[i]?'completed':''}"><p class="eyebrow">${d}</p><h3>${i===4?'Revisão + noivado':'Revisão trimestral'}</h3><p>Conferir renda, aportes, orçamento e decisões pendentes.</p><label><input data-review="${i}" type="checkbox" ${state.reviews[i]?'checked':''}> ${state.reviews[i]?'Concluída':'Marcar como concluída'}</label></article>`).join('');$$('[data-review]').forEach(i=>i.onchange=()=>{state.reviews[i.dataset.review]=i.checked;save()})}
function renderSettings(){const f=$('#settings-form');['initial','cideMonthly','rebecaMonthly','months','reserveFloor','cideShare'].forEach(k=>f.elements[k].value=state[k])}
$('#settings-form').onsubmit=e=>{e.preventDefault();new FormData(e.target).forEach((v,k)=>state[k]=Number(v));save();toast('Premissas salvas')};
function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#print').onclick=()=>print();$('#json').onclick=()=>download('alianca-financeira-backup.json','application/json',JSON.stringify(state,null,2));$('#csv').onclick=()=>{const rows=[['Indicador','Valor'],['Capital inicial',state.initial],['Aporte Cide',state.cideMonthly],['Aporte Rebeca',state.rebecaMonthly],['Meses',state.months],['Meta total',totalGoal()],['Projeção',projected()],['Diferença',Math.max(0,totalGoal()-projected())]];download('alianca-financeira-relatorio.csv','text/csv;charset=utf-8','\ufeff'+rows.map(r=>r.join(';')).join('\n'))};
$('#import').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=merge(DEFAULT,JSON.parse(reader.result));save();toast('Cópia restaurada')}catch{toast('Arquivo inválido')}};reader.readAsText(file)};$('#reset').onclick=()=>{if(confirm('Restaurar todos os dados de demonstração?')){state=structuredClone(DEFAULT);save();toast('Plano restaurado')}};
function renderAll(){renderDashboard();renderGoals();renderBudget();renderContributions();renderTimeline();renderScenario();renderHome();renderReviews();renderSettings()}
window.addEventListener('resize',drawChart);window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'dashboard'));renderAll();showView(location.hash.slice(1)||'dashboard');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}))}